services:
  db:
    profiles:
      - dev
    image: postgres:18-trixie
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: always
    volumes:
      - type: volume
        source: basic_web_db_data
        target: /var/lib/postgresql
        volume:
          nocopy: true
    ports:
      - "5432:5432"
  ui:
    profiles:
      - dev
    image: dpage/pgadmin4:9
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      # servers.json で使用する環境変数をpgAdminコンテナに渡す
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      # pgAdmin に servers.json の場所を教える
      PGADMIN_SERVER_JSON_FILE: /var/lib/pgadmin/servers/servers.json
    ports:
      - "8080:80"
    volumes:
      - basic_web_pgadmin_data:/var/lib/pgadmin
      - ./config/servers.json.template:/pgadmin4/servers.json.template
      - ./pgadmin_entrypoint.sh:/pgadmin_entrypoint.sh
    entrypoint: [ "/bin/bash", "/pgadmin_entrypoint.sh" ]
    depends_on:
      - db
  test_db:
    profiles:
      - test
    image: postgres:18-trixie
    container_name: test_pg
    environment:
      POSTGRES_USER: ${DATABASE_TEST_USER}
      POSTGRES_PASSWORD: ${DATABASE_TEST_PASSWORD}
      POSTGRES_DB: ${DATABASE_TEST_NAME}
    restart: always
    tmpfs:
      - /var/lib/postgresql
    ports:
      - "${DATABASE_TEST_PORT}:5432"
volumes:
  basic_web_db_data:
  basic_web_pgadmin_data: