@param String title = null

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>
    @if(title != null)
        ${title} | Basic Web
    @else
        Basic Web
    @endif
</title>

<link rel="stylesheet" href="/webjars/bootswatch-flatly/5.3.3/bootstrap.min.css">
<script defer src="/webjars/bootstrap/5.3.3/js/bootstrap.bundle.min.js"></script>

<link rel="stylesheet" href="/css/app.css">

<script src="http://localhost:35729/livereload.js"></script>
